version: "3.8"

services:
  mariadb:
    image: mariadb:10.11
    container_name: express-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ""
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: monitor_suhu
      MARIADB_USER: root
      MARIADB_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./src/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  volumes:
    mariadb_data:
